node26.cluster
/home/unibas/boittier/FDCM/fbuta_2/0_1
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-0-1.xyz’: No such file or directory

real	0m0.012s
user	0m0.002s
sys	0m0.002s
-xyz
refined.xyz
-dens
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/1_SCAN_1_2_3_4_F/B.d.cube
-esp
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/1_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/1_SCAN_1_2_3_4_F/B.p.cube".
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/1_2
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-1-2.xyz’: No such file or directory

real	0m0.023s
user	0m0.001s
sys	0m0.003s
-xyz
refined.xyz
-dens
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/2_SCAN_1_2_3_4_F/B.d.cube
-esp
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/2_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/2_SCAN_1_2_3_4_F/B.p.cube".
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/2_3
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-2-3.xyz’: No such file or directory

real	0m0.037s
user	0m0.002s
sys	0m0.001s
-xyz
refined.xyz
-dens
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/3_SCAN_1_2_3_4_F/B.d.cube
-esp
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/3_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/3_SCAN_1_2_3_4_F/B.p.cube".
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/3_4
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-3-4.xyz’: No such file or directory

real	0m0.233s
user	0m0.001s
sys	0m0.003s
-xyz
refined.xyz
-dens
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/4_SCAN_1_2_3_4_F/B.d.cube
-esp
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/4_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/4_SCAN_1_2_3_4_F/B.p.cube".
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/4_5
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-4-5.xyz’: No such file or directory

real	0m0.304s
user	0m0.001s
sys	0m0.002s
-xyz
refined.xyz
-dens
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/5_SCAN_1_2_3_4_F/B.d.cube
-esp
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/5_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/5_SCAN_1_2_3_4_F/B.p.cube".
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/5_6
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-5-6.xyz’: No such file or directory

real	0m0.180s
user	0m0.000s
sys	0m0.004s
-xyz
refined.xyz
-dens
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/6_SCAN_1_2_3_4_F/B.d.cube
-esp
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/6_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/6_SCAN_1_2_3_4_F/B.p.cube".
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/6_7
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-6-7.xyz’: No such file or directory

real	0m0.150s
user	0m0.000s
sys	0m0.004s
-xyz
refined.xyz
-dens
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/7_SCAN_1_2_3_4_F/B.d.cube
-esp
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/7_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/7_SCAN_1_2_3_4_F/B.p.cube".
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/7_8
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-7-8.xyz’: No such file or directory

real	0m0.375s
user	0m0.001s
sys	0m0.002s
-xyz
refined.xyz
-dens
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/8_SCAN_1_2_3_4_F/B.d.cube
-esp
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/8_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/8_SCAN_1_2_3_4_F/B.p.cube".
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/8_9
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-8-9.xyz’: No such file or directory

real	0m0.055s
user	0m0.000s
sys	0m0.004s
-xyz
refined.xyz
-dens
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/9_SCAN_1_2_3_4_F/B.d.cube
-esp
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/9_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/9_SCAN_1_2_3_4_F/B.p.cube".
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/9_10
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-9-10.xyz’: No such file or directory

real	0m0.637s
user	0m0.001s
sys	0m0.002s
-xyz
refined.xyz
-dens
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/10_SCAN_1_2_3_4_F/B.d.cube
-esp
~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/10_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "~/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_10_36/fbuta_2/10_SCAN_1_2_3_4_F/B.p.cube".
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/10_11
slurmstepd: error: *** JOB 38322395 ON node26 CANCELLED AT 2021-10-01T10:34:18 ***
